name: Publish CUE module
"on":
  push:
    tags:
      - '*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: cue-lang/setup-cue@v1.0.1
      - uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: cue mod publish ${{ github.ref_name }}
        env:
          CUE_REGISTRY: ${{ env.REGISTRY }}
